# Selection
# DATASETS = {
#     1: 'BCICIV2a',
#     2: 'BCICIV2b',
#     3: 'XWStroke',
# }
dataset_id: 3
# MODELS = {
#     1: 'EEGNet',
#     2: 'CNNLSTM',
#     3: 'ADFCNN',
#     4: 'MultiBand_CNNLSTM',
#     5: 'Simplified_MultiBand_CNNLSTM',
# }
model_id: 3

# Mode
# is_test = False

# Training Config
Training:
  target_subjects: [1]
  train_device: 'cuda'
  batch_size: 16
  num_epochs: 30
  learning_rate: 0.001
  weight_decay: 0.075
  k_folds: 5