# Selection
# DATASETS = {
#     1: 'BCICIV2a',
#     2: 'BCICIV2b',
#     3: 'XWStroke',
# }
dataset_id: 3
# MODELS = {
#     1: 'EEGNet',
#     2: 'CNNLSTM',
#     3: 'ADFCNN',
#     4: 'MultiBand_CNNLSTM',
#     5: 'Simplified_MultiBand_CNNLSTM',
# }
model_id: 3

# Mode
model: "train"  # "train", "evaluate", "predict"

# Training Config
Training:
  target_subjects: "all"
  train_device: 'cuda'
  batch_size: 32
  num_epochs: 200
  learning_rate: 0.001
  weight_decay: 0.5
  k_folds: 5
  random_seed: 42