# Selection
# DATASETS = {
#     1: 'BCICIV2a',
#     2: 'BCICIV2b',
#     3: 'XWStroke',
#     4: 'LowerStroke',
# }
dataset_id: 3
# MODELS = {
#     1: 'EEGNet',
#     2: 'CNNLSTM',
#     3: 'ADFCNN',
#     4: 'MultiBand_CNNLSTM',
#     5: 'Simplified_MultiBand_CNNLSTM',
#     6: 'FilterBankCNN'
#     7: 'FBCNet_Standard',
# }
model_id: 3

# Mode
model: "train"  # "train", "evaluate", "predict"

# Training Config
Training:
  target_subjects: "all"
  # target_subjects: [7, 11, 22, 40, 45]
  # target_subjects: [11]
  # target_subjects: [4, 5, 13, 14, 18, 24, 28, 33, 42, 43, 47, 48, 49]
  # target_subjects: [3, 17, 25]
  train_device: 'cuda'
  batch_size: 32
  num_epochs: 200
  learning_rate: 0.001
  weight_decay: 0.5
  k_folds: 5
  random_seed: 42