dataset:
  EOG_channels:
  - 30
  - 31
  data_dir: src/datasets/21679035/sourcedata
  data_var_name: eeg_data_4s
  labels:
  - 1
  - 2
  labels_var_name: labels
  name: XWStroke
  num_channels: 32
  num_classes: 2
  num_subjects: 50
  original_sr: 500
  raw_data_dir: src/datasets/21679035/sourcedata
  subjects:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  use_4s_data: true
pipelines:
  augmentation_pipeline: []
  global_pipeline:
  - name: resample
  - name: channel_selection
  - name: filter_bank
  sample_pipeline: []
preprocessing:
  augmentation:
  - method: add_noise
    probability: 0
    snr_db: 20
  - dropout_rate: 0.1
    method: channel_dropout
    probability: 0
  - method: time_warp
    probability: 0
    sigma: 0.2
  channel_selection:
    channels_to_select:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  euclidean_alignment:
    enabled: true
    eps: 1.0e-10
  filter_bank:
    filter_banks:
    - - 0.5
      - 100
    normalize: true
  normalization:
    method: none
  resample:
    target_sr: 500
  windowing:
    window_length_sec: 4.0
    window_stride_sec: 4.0
