data_dir: "src/datasets/BCICIV2a"

task: "BCICompetIV2a"
num_classes: 4
num_channels: 22
channels_selected: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

num_subjects: 9
sample_rate: 250